before_script:
  - apt-get update
  - apt-get -y install awscli

stages:
  - deploy

ci_build_and_deploy:
  stage: deploy
  image: node:10
  script:
    - npm install
    - npm run build
    - cd build
    - aws s3 cp ./ s3://hiett.digital/ --recursive
  only:
    - master
